
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet tool restore

vscode:
  extensions:
    - Ionide.Ionide-fsharp
    - EditorConfig.EditorConfig
    - PKief.material-icon-theme
    - ionutvmi.path-autocomplete
